"""Build packed token shards from local text/JSONL or Hugging Face datasets.

Examples:
    # Local synthetic reasoning traces generated by Ollama/Qwen.
    PYTHONPATH=src python scripts/build_token_shards.py \
      --input data/reasoning/qwen36_reasoning.jsonl \
      --tokenizer Qwen/Qwen2.5-1.5B \
      --out data/packed/qwen36_reasoning_qwen_tok

    # Dependency-free smoke path.
    PYTHONPATH=src python scripts/build_token_shards.py \
      --input prompts/reasoning_seeds.jsonl --tokenizer byte --out /tmp/plasma_packed_smoke
"""

from __future__ import annotations

import argparse
import glob
import json
from pathlib import Path
from typing import Iterable, Iterator

import numpy as np


CHAT_KEYS = ("text", "completion", "response", "output", "answer")


class ByteTokenizer:
    name_or_path = "byte"
    vocab_size = 256
    eos_token_id = None

    def encode(self, text: str, add_special_tokens: bool = False) -> list[int]:
        return list(text.encode("utf-8"))


def load_tokenizer(name: str):
    if name == "byte":
        return ByteTokenizer()
    try:
        from transformers import AutoTokenizer  # type: ignore
    except Exception as exc:
        raise SystemExit(
            "transformers is required for non-byte tokenizers. Install with: pip install -e '.[scale]'"
        ) from exc
    tok = AutoTokenizer.from_pretrained(name, trust_remote_code=True)
    if tok.eos_token_id is None and tok.pad_token_id is not None:
        tok.eos_token_id = tok.pad_token_id
    return tok


def iter_local_records(patterns: list[str], text_column: str) -> Iterator[str]:
    paths: list[Path] = []
    for pattern in patterns:
        matches = [Path(p) for p in glob.glob(pattern)]
        paths.extend(matches if matches else [Path(pattern)])
    for path in paths:
        if not path.exists():
            raise FileNotFoundError(path)
        if path.suffix == ".jsonl":
            with path.open("r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    if not line.strip():
                        continue
                    obj = json.loads(line)
                    yield record_to_text(obj, text_column)
        elif path.suffix == ".json":
            obj = json.loads(path.read_text(encoding="utf-8", errors="replace"))
            if isinstance(obj, list):
                for item in obj:
                    yield record_to_text(item, text_column)
            else:
                yield record_to_text(obj, text_column)
        else:
            yield path.read_text(encoding="utf-8", errors="replace")


def iter_hf_records(dataset: str, split: str, text_column: str,
                    dataset_config: str | None = None) -> Iterator[str]:
    try:
        from datasets import load_dataset  # type: ignore
    except Exception as exc:
        raise SystemExit(
            "datasets is required for --hf-dataset. Install with: pip install -e '.[scale]'"
        ) from exc
    ds = load_dataset(dataset, dataset_config, split=split, streaming=True)
    for row in ds:
        yield record_to_text(row, text_column)


def record_to_text(obj, text_column: str) -> str:
    if isinstance(obj, str):
        return obj
    if not isinstance(obj, dict):
        return str(obj)
    if text_column in obj and obj[text_column] is not None:
        return str(obj[text_column])
    if "messages" in obj and isinstance(obj["messages"], list):
        return messages_to_chatml(obj["messages"])
    if "prompt" in obj and any(k in obj for k in CHAT_KEYS):
        answer = next((obj[k] for k in CHAT_KEYS if k in obj and obj[k] is not None), "")
        return f"<|user|>\n{obj['prompt']}\n<|assistant|>\n{answer}\n"
    if "prompt" in obj:
        return f"<|user|>\n{obj['prompt']}\n"
    for key in CHAT_KEYS:
        if key in obj and obj[key] is not None:
            return str(obj[key])
    raise KeyError(f"could not find text in record; keys={list(obj.keys())}")


def messages_to_chatml(messages: list[dict]) -> str:
    parts = []
    for msg in messages:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        parts.append(f"<|{role}|>\n{content}\n")
    return "".join(parts)


def choose_dtype(vocab_size: int) -> str:
    return "uint16" if vocab_size <= 65535 else "uint32"


def write_ids(f, ids: list[int], dtype: str) -> int:
    if not ids:
        return 0
    arr = np.asarray(ids, dtype=np.uint16 if dtype == "uint16" else np.uint32)
    arr.tofile(f)
    return int(arr.size)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", action="append", default=[], help="local text/json/jsonl path or glob")
    ap.add_argument("--hf-dataset", default=None, help="optional Hugging Face dataset name")
    ap.add_argument("--hf-config", default=None)
    ap.add_argument("--hf-split", default="train")
    ap.add_argument("--text-column", default="text")
    ap.add_argument("--tokenizer", required=True, help="HF tokenizer name/path, or 'byte'")
    ap.add_argument("--out", required=True, help="output packed dataset directory")
    ap.add_argument("--max-docs", type=int, default=0)
    ap.add_argument("--validation-every", type=int, default=1000,
                    help="send every Nth document to validation")
    ap.add_argument("--append-eos", action="store_true", default=True)
    ap.add_argument("--no-eos", dest="append_eos", action="store_false")
    args = ap.parse_args()

    if not args.input and not args.hf_dataset:
        raise SystemExit("provide --input and/or --hf-dataset")

    tokenizer = load_tokenizer(args.tokenizer)
    vocab_size = int(getattr(tokenizer, "vocab_size", 0) or len(getattr(tokenizer, "get_vocab", lambda: {})()))
    if vocab_size <= 0:
        vocab_size = 256 if args.tokenizer == "byte" else 100000
    dtype = choose_dtype(vocab_size)

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    train_path = out_dir / "train.bin"
    val_path = out_dir / "validation.bin"

    sources: list[Iterable[str]] = []
    if args.input:
        sources.append(iter_local_records(args.input, args.text_column))
    if args.hf_dataset:
        sources.append(iter_hf_records(args.hf_dataset, args.hf_split, args.text_column, args.hf_config))

    counts = {"train_docs": 0, "validation_docs": 0, "train_tokens": 0, "validation_tokens": 0}
    max_token_id = 0
    doc_i = 0
    import time as _time
    print(f"=== build_token_shards ===", flush=True)
    print(f"tokenizer: {args.tokenizer} (vocab_size={vocab_size}, dtype={dtype})", flush=True)
    print(f"inputs   : {args.input or '(none)'} hf={args.hf_dataset or '(none)'}", flush=True)
    print(f"out      : {out_dir}", flush=True)
    print(f"val_every: every {args.validation_every}th doc -> validation split", flush=True)
    heartbeat_every = max(100, args.validation_every)
    t0 = _time.monotonic()
    with train_path.open("wb") as train_f, val_path.open("wb") as val_f:
        for source in sources:
            for text in source:
                doc_i += 1
                if args.max_docs and doc_i > args.max_docs:
                    break
                ids = tokenizer.encode(text, add_special_tokens=False)
                if args.append_eos and getattr(tokenizer, "eos_token_id", None) is not None:
                    ids = ids + [int(tokenizer.eos_token_id)]
                if ids:
                    max_token_id = max(max_token_id, max(int(x) for x in ids))
                is_val = args.validation_every > 0 and doc_i % args.validation_every == 0
                if is_val:
                    counts["validation_docs"] += 1
                    counts["validation_tokens"] += write_ids(val_f, ids, dtype)
                else:
                    counts["train_docs"] += 1
                    counts["train_tokens"] += write_ids(train_f, ids, dtype)
                if doc_i % heartbeat_every == 0:
                    dt = max(_time.monotonic() - t0, 1e-6)
                    rate = doc_i / dt
                    tok_total = counts["train_tokens"] + counts["validation_tokens"]
                    print(f"~~ {doc_i} docs | train={counts['train_docs']} val={counts['validation_docs']} "
                          f"| tokens={tok_total} | {rate:.1f} docs/s | {dt:.1f}s elapsed", flush=True)
            if args.max_docs and doc_i >= args.max_docs:
                break
    dt = max(_time.monotonic() - t0, 1e-6)
    print(f"=== finished tokenization | {doc_i} docs in {dt:.1f}s ({doc_i/dt:.1f} docs/s) ===", flush=True)

    if counts["validation_tokens"] == 0:
        raise SystemExit("validation split is empty; lower --validation-every or provide more docs")
    meta = {
        "format": "phi_plasma_packed_tokens_v1",
        "dtype": dtype,
        "vocab_size": vocab_size,
        "max_token_id": max_token_id,
        "tokenizer_name": args.tokenizer if args.tokenizer != "byte" else None,
        "tokenizer_path": args.tokenizer if Path(args.tokenizer).exists() else None,
        "append_eos": args.append_eos,
        "text_column": args.text_column,
        "sources": {"inputs": args.input, "hf_dataset": args.hf_dataset, "hf_config": args.hf_config, "hf_split": args.hf_split},
        "splits": {
            "train": {"path": "train.bin", "docs": counts["train_docs"], "tokens": counts["train_tokens"]},
            "validation": {"path": "validation.bin", "docs": counts["validation_docs"], "tokens": counts["validation_tokens"]},
        },
    }
    (out_dir / "meta.json").write_text(json.dumps(meta, indent=2) + "\n")
    print(json.dumps(meta, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
